#user
cms_core.user_register:
  pattern: /user/register/{account_type}
  defaults: { _controller: CmsCoreBundle:User:register, account_type = 'free' }
  methods: [GET]

cms_core.user_create:
  pattern: /user/create
  defaults: { _controller: CmsCoreBundle:User:create }
  methods: [POST]

cms_core.user_save:
  pattern:  /user
  defaults: { _controller: CmsCoreBundle:User:save }
  methods: [POST]

#landing
_welcome:
  pattern: /
  defaults: { _controller: CmsCoreBundle:Welcome:index }
  methods: [GET]

#app
cms_core.app_index:
  pattern: /app
  defaults: { _controller: CmsCoreBundle:App:Index }
  methods: [GET]

#site
cms_core.site_save:
  pattern: /site
  defaults: { _controller: CmsCoreBundle:Site:save }
  methods: [POST]

cms_core.site_settings:
  pattern: /site/settings/{id}
  defaults: { _controller: CmsCoreBundle:Site:settings }
  methods: [GET]

cms_core.site_read:
  pattern: /site/{id}
  defaults: { _controller: CmsCoreBundle:Site:read }
  methods: [GET]

cms_core.site_delete:
  pattern: /site/delete
  defaults: { _controller: CmsCoreBundle:Site:delete }
  methods: [POST]


#contentType
cms_core.contentType_save:
  pattern: /contentType
  defaults: { _controller: CmsCoreBundle:ContentType:save }
  methods: [POST]

cms_core.contentType_settings:
  pattern: /contentType/settings/{siteId}/{id}
  defaults: { _controller: CmsCoreBundle:ContentType:settings }
  methods: [GET]

cms_core.contentType_read:
  pattern: /contentType/{siteId}/{id}
  defaults: { _controller: CmsCoreBundle:ContentType:read }
  methods: [GET]

cms_core.contentType_delete:
  pattern: /contentType/delete
  defaults: { _controller: CmsCoreBundle:ContentType:delete }
  methods: [POST]

cms_core.contentType_addCategory:
  pattern: /contentType/addCategory
  defaults: { _controller: CmsCoreBundle:ContentType:addCategory }
  methods: [POST]

#node
cms_core.node_delete:
  pattern: /node/delete
  defaults: { _controller: CmsCoreBundle:Node:delete }
  methods: [POST]

cms_core.node_save:
  pattern: /node
  defaults: { _controller: CmsCoreBundle:Node:save }
  methods: [POST]

cms_core.node_new:
  pattern: /node/new/{siteId}/{contentTypeId}
  defaults: { _controller: CmsCoreBundle:Node:new }
  methods: [GET]

cms_core.node_read:
  pattern: /node/{id}
  defaults: { _controller: CmsCoreBundle:Node:read }
  methods: [GET]


#template
cms_core.template_components_save:
  pattern: /template/components
  defaults: { _controller: CmsCoreBundle:Template:saveComponents }
  methods: [POST]

cms_core.template_new:
  pattern: /template/new
  defaults: { _controller: CmsCoreBundle:Template:new }
  methods: [GET]

cms_core.template_delete:
  pattern: /template/delete
  defaults: { _controller: CmsCoreBundle:Template:delete }
  methods: [POST]

cms_core.template_readAll:
  pattern: /templates
  defaults: { _controller: CmsCoreBundle:Template:readAll }
  methods: [GET]

cms_core.template_read:
  pattern: /template/{id}
  defaults: { _controller: CmsCoreBundle:Template:read }
  methods: [GET]

cms_core.template_save:
  pattern: /template
  defaults: { _controller: CmsCoreBundle:Template:save }
  methods: [POST]

cms_core.template_menu:
  pattern: /template/menu/{siteId}
  defaults: { _controller: CmsCoreBundle:Template:menu }
  methods: [GET]

#themeOrg
cms_core.themeOrg_save:
  pattern: /theme-org/save
  defaults: { _controller: CmsCoreBundle:ThemeOrg:save }
  methods: [POST]

cms_core.themeOrg_read:
  pattern: /theme-org/edit/{id}
  defaults: { _controller: CmsCoreBundle:ThemeOrg:read }
  methods: [GET]

cms_core.themeOrg_new:
  pattern: /theme-org/new
  defaults: { _controller: CmsCoreBundle:ThemeOrg:new }
  methods: [GET]

cms_core.themeOrg_readAll:
  pattern: /theme-org/read-all
  defaults: { _controller: CmsCoreBundle:ThemeOrg:readAll }
  methods: [GET]

cms_core.themeOrg_delete:
  pattern: /theme-org/delete
  defaults: { _controller: CmsCoreBundle:ThemeOrg:delete }
  methods: [POST]

#theme
cms_core.theme_wizard:
  pattern: /theme/wizard/{orgId}
  defaults: { _controller: CmsCoreBundle:Theme:wizard }
  methods: [GET]

cms_core.theme_delete:
  pattern: /theme/delete
  defaults: { _controller: CmsCoreBundle:Theme:delete }
  methods: [POST]

cms_core.theme_new:
  pattern: /theme/new
  defaults: { _controller: CmsCoreBundle:Theme:new }
  methods: [GET]

cms_core.theme_readAll:
  pattern: /themes/{orgId}
  defaults: { _controller: CmsCoreBundle:Theme:readAll }
  methods: [GET]

cms_core.theme_read:
  pattern: /theme/{id}
  defaults: { _controller: CmsCoreBundle:Theme:read }
  methods: [GET]

cms_core.theme_save:
  pattern: /theme
  defaults: { _controller: CmsCoreBundle:Theme:save }
  methods: [POST]

#assets
cms_core.asset_delete:
  pattern: /asset/delete
  defaults: { _controller: CmsCoreBundle:Asset:delete }
  methods: [POST]

cms_core.asset_new:
  pattern: /asset/new/{siteId}
  defaults: { _controller: CmsCoreBundle:Asset:new }
  methods: [GET]

cms_core.asset_readAll:
  pattern: /assets/{siteId}
  defaults: { _controller: CmsCoreBundle:Asset:readAll }
  methods: [GET]

cms_core.asset_read:
  pattern: /asset/{id}
  defaults: { _controller: CmsCoreBundle:Asset:read }
  methods: [GET]

cms_core.asset_save:
  pattern: /asset
  defaults: { _controller: CmsCoreBundle:Asset:save }
  methods: [POST]

#media
cms_core.media_new:
  pattern: /media/new/{siteId}
  defaults: { _controller: CmsCoreBundle:Media:new }
  methods: [GET]

cms_core.media_create:
  pattern: /media
  defaults: { _controller: CmsCoreBundle:Media:create }
  methods: [POST]

cms_core.media_add:
  pattern: /media/add
  defaults: { _controller: CmsCoreBundle:Media:add }
  methods: [POST]

cms_core.media_readAll:
  pattern: /media/all/{siteId}
  defaults: { _controller: CmsCoreBundle:Media:readAll }
  methods: [GET]

cms_core.media_read:
  pattern: /media/{siteId}/{id}
  defaults: { _controller: CmsCoreBundle:Media:read }
  methods: [GET]

cms_core.media_update:
  pattern: /media/update
  defaults: { _controller: CmsCoreBundle:Media:update }
  methods: [POST]

cms_core.media_delete:
  pattern: /media/delete
  defaults: { _controller: CmsCoreBundle:Media:delete }
  methods: [POST]

#session routes
cms_core.session_notices:
  pattern: /session/notices.{json}
  defaults: { _controller: CmsCoreBundle:Session:getNotices, _format: json }
  methods: [GET]
  requirements:
    _format: json


#client routes
cms_core.read_locale_nodes:
  pattern: /{_locale}/{path}
  defaults: { _controller: CmsCoreBundle:Default:nodeRead }
  requirements:
    _locale: "[a-z]{2}-[a-z]{2}"
    path: ".+"

cms_core.read_nodes:
  pattern: /{path}
  defaults:  { _controller: CmsCoreBundle:Default:nodeRead }
  requirements:
    path: ".+"

cms_core.read_nodes_null_path:
  pattern: /
  defaults: { _controller: CmsCoreBundle:Default:nodeRead }