cms_api_v1.nodes_read:
  pattern: /nodes/{ids}.{_format}
  defaults: { _controller: CmsCoreBundle:Api:nodeReadV1, _format: 'json' }
  methods: [GET]
  requirements:
    _format: '(json|xml)'

cms_api_v1.nodes_readAll:
  pattern: /nodes.{_format}
  defaults: { _controller: CmsCoreBundle:Api:NodeReadAllV1, _format: 'json' }
  methods: [GET]
  requirements:
    _format: '(json|xml)'

cms_api_v1.nodes_create:
  pattern: /nodes.{_format}
  defaults: { _controller: CmsCoreBundle:Api:nodeCreate, _format: 'json' }
  methods: [POST]
  requirements:
    _format: '(json|xml)'


cms_api_v1.test:
  pattern: /test
  defaults: { _controller: CmsCoreBundle:Api:test }
  methods: [GET]

cms_api_v1.token:
  pattern: /token
  defaults: { _controller: CmsCoreBundle:Api:token }
  methods: [GET]