cms_api_v1.node_find:
  pattern: /nodes/find
  defaults: { _controller: CmsCoreBundle:Api:nodeFindV1, _format: 'json' }
  methods: [GET]

cms_api_v1.node_search:
  pattern: /nodes/search
  defaults: { _controller: CmsCoreBundle:Api:nodeSearchV1, _format: 'json' }
  methods: [GET]

cms_api_v1.node_read:
  pattern: /nodes/{id}
  defaults: { _controller: CmsCoreBundle:Api:nodeReadV1, _format: 'json' }
  methods: [GET]

cms_api_v1.loop_find:
  pattern: /loops/find
  defaults: { _controller: CmsCoreBundle:Api:loopFindV1, _format: 'json' }
  methods: [GET]



cms_api_v1.test:
  pattern: /test
  defaults: { _controller: CmsCoreBundle:Api:test }
  methods: [GET]

cms_api_v1.token:
  pattern: /token
  defaults: { _controller: CmsCoreBundle:Api:token }
  methods: [GET]

#cms_core.api_read_locale_nodes:
#  pattern: /{_locale}/{path}
#  defaults: { _controller: CmsCoreBundle:Client:apiNodeRead }
#  methods: [GET]
#  requirements:
#    _locale: "[a-z]{2}-[a-z]{2}"
#    path: ".+"
#
#cms_core.api_v1_read_node:
#  pattern: /node/{path}
#  defaults:  { _controller: CmsCoreBundle:Client:apiNodeRead }
#  methods: [GET]
#  requirements:
#    path: ".+"
#
#cms_core.api_v1_read_loop:
#  pattern: /loop/{path}
#  defaults:  { _controller: CmsCoreBundle:Client:apiLoopRead }
#  methods: [GET]
#  requirements:
#    path: ".+"
#
#cms_core.api_read_nodes_null_path:
#  pattern: /
#  defaults: { _controller: CmsCoreBundle:Client:apiNodeRead }
#  methods: [GET]
#
#cms_core.api_v1_save_node:
#  pattern: /node
#  defaults: { _controller: CmsCoreBundle:Node:apiSave }
#  methods: [GET, POST]