#user
cms_core.user_register:
  pattern: /user/register/{accountPlan}
  defaults: { _controller: CmsCoreBundle:User:register, accountPlan: free }
  methods: [GET]

cms_core.user_create:
  pattern: /user/create
  defaults: { _controller: CmsCoreBundle:User:create }
  methods: [POST]
cms_core.user_save:
  pattern:  /user
  defaults: { _controller: CmsCoreBundle:User:save }
  methods: [POST]

#landing
_welcome:
  pattern: /
  defaults: { _controller: CmsCoreBundle:Welcome:index }
  methods: [GET]

welcome.about:
  pattern: /about
  defaults: { _controller: CmsCoreBundle:Welcome:about }
  methods: [GET]

welcome.about_slides:
  pattern: /about/slides
  defaults: { _controller: CmsCoreBundle:Welcome:aboutSlides }
  methods: [GET]

#app help
cms_core.help:
  pattern: /help
  defaults: { _controller: CmsCoreBundle:Help:index }
  methods: [GET]

#developers
cms_core.developers:
  pattern: /developers
  defaults: { _controller: CmsCoreBundle:Developers:index }
  methods: [GET]

cms_core.developers_basics:
  pattern: /developers/basics
  defaults: { _controller: CmsCoreBundle:Developers:basics }
  methods: [GET]

cms_core.developers_responses:
  pattern: /developers/responses
  defaults: { _controller: CmsCoreBundle:Developers:responses }
  methods: [GET]

cms_core.developers_exceptions:
  pattern: /developers/exceptions
  defaults: { _controller: CmsCoreBundle:Developers:exceptions }
  methods: [GET]

cms_core.developers_endpoint_nodes:
  pattern: /developers/endpoint/nodes
  defaults: { _controller: CmsCoreBundle:Developers:endpointNodes }
  methods: [GET]

cms_core.developers_endpoint_media:
  pattern: /developers/endpoint/media
  defaults: { _controller: CmsCoreBundle:Developers:endpointMedia }
  methods: [GET]

cms_core.developers_endpoint_types:
  pattern: /developers/endpoint/types
  defaults: { _controller: CmsCoreBundle:Developers:endpointTypes }
  methods: [GET]

cms_core.developers_endpoint_sites:
  pattern: /developers/endpoint/sites
  defaults: { _controller: CmsCoreBundle:Developers:endpointSites }
  methods: [GET]

cms_core.developers_sdk_php:
  pattern: /developers/sdk/php
  defaults: { _controller: CmsCoreBundle:Developers:sdkPhp }
  methods: [GET]

cms_core.developers_demos:
  pattern: /developers/demos
  defaults: { _controller: CmsCoreBundle:Developers:demos }
  methods: [GET]

cms_core.developers_tutorial_jqm:
  pattern: /developers/tutorial/jquery-mobile
  defaults: { _controller: CmsCoreBundle:Developers:tutorialJqm }
  methods: [GET]