cms_core.user_register:
  pattern: /user/register
  defaults: { _controller: CmsCoreBundle:User:Register }
  methods: [GET]

cms_core.user_save:
  pattern:  /user
  defaults: { _controller: CmsCoreBundle:User:Save }
  methods: [POST]


cms_core.app_index:
  pattern: /app
  defaults: { _controller: CmsCoreBundle:App:Index }
  methods: [GET]


cms_core.site_save:
  pattern: /site
  defaults: { _controller: CmsCoreBundle:Site:save }
  methods: [POST]

cms_core.site_read:
  pattern: /site/{id}
  defaults: { _controller: CmsCoreBundle:Site:read }
  methods: [GET]


cms_core.contentType_save:
  pattern: /contentType
  defaults: { _controller: CmsCoreBundle:ContentType:save }
  methods: [POST]

#node crud :)



#client routes
cms_core.read_locale_nodes:
  pattern: /{_locale}/{path}
  defaults: { _controller: CmsCoreBundle:Default:nodeRead }
  requirements:
    _locale: "[a-z]{2}-[a-z]{2}"
    path: ".+"

cms_core.read_nodes:
  pattern: /{path}
  defaults:  { _controller: CmsCoreBundle:Default:nodeRead }
  requirements:
    path: ".+"

cms_core.read_nodes_null_path:
  pattern: /
  defaults: { _controller: CmsCoreBundle:Default:nodeRead }