#user
cms_core.user_register:
  pattern: /user/register/{account_type}
  defaults: { _controller: CmsCoreBundle:User:register, account_type = 'free' }
  methods: [GET]

cms_core.user_create:
  pattern: /user/create
  defaults: { _controller: CmsCoreBundle:User:create }
  methods: [POST]

cms_core.user_save:
  pattern:  /user
  defaults: { _controller: CmsCoreBundle:User:save }
  methods: [POST]

#landing
_welcome:
  pattern: /
  defaults: { _controller: CmsCoreBundle:Welcome:index }
  methods: [GET]

welcome.about:
  pattern: /about
  defaults: { _controller: CmsCoreBundle:Welcome:about }
  methods: [GET]

welcome.about_slides:
  pattern: /about/slides
  defaults: { _controller: CmsCoreBundle:Welcome:aboutSlides }
  methods: [GET]

#app help
cms_core.help:
  pattern: /help
  defaults: { _controller: CmsCoreBundle:Help:index }
  methods: [GET]

#developers
cms_core.developers:
  pattern: /developers
  defaults: { _controller: CmsCoreBundle:Developers:index }
  methods: [GET]