parameters:
    cms.local_asset_manager.class: Cms\CoreBundle\Services\AssetManager\Local
    cms.mongo_twig_load.class: Cms\CoreBundle\Services\TemplateLoader\MongoTwigLoader
    cms.twig_environemnt.class: Cms\CoreBundle\Services\TemplateLoader\TwigEnvironment
    cms.node_loop_finder.class: Cms\CoreBundle\Services\NodeLoader\LoopFinder
    cms.node_loop_loader.class: Cms\CoreBundle\Services\NodeLoader\CoreLoop
    cms.param_manager.class: Cms\CoreBundle\Services\ParamManager\Core
    cms.node_loader.class: Cms\CoreBundle\Services\NodeLoader\CoreNode
    cms.namespace_helper.class: Cms\CoreBundle\Services\NamespaceHelper
    cms.media_manager.class: Cms\CoreBundle\Services\MediaManager\Manager
    aws.key.param: AKIAJN6IC7B5YOWD627Q
    aws.secret.param: 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
    aws.s3_storage_factory.class: Cms\CoreBundle\Services\MediaManager\S3StorageFactory
    cms.slug_helper.class: Cms\CoreBundle\Services\SlugHelper
    cms.template_client.class: Cms\CoreBundle\Services\TemplateLoader\Client
    cms.template_helper.class: Cms\CoreBundle\Services\TemplateLoader\Helper
    cms.theme_template_helper.class: Cms\CoreBundle\Services\ThemeTemplateHelper
    cms.site_manager_unique.class: Cms\CoreBundle\Services\SiteManager\unique
    cms.api_access_token.class: Cms\CoreBundle\Services\Api\Token
    cms.check_route.class: Cms\CoreBundle\Services\CheckRoute
    cms.api_node_adopter.class: Cms\CoreBundle\Services\Api\EntityAdopters\NodeAdopter

services:
    asset_manager:
        class: %cms.local_asset_manager.class%
    template_loader:
        class: %cms.mongo_twig_load.class%
        arguments: [@doctrine.odm.mongodb.document_manager, CmsCoreBundle:Template ]
    twig_loader:
        class: %cms.twig_environemnt.class%
        arguments: [@kernel]
        calls:
          - [setLoader, [@template_loader]]
    template_client:
        class: %cms.template_client.class%
    template_helper:
        class: %cms.template_helper.class%
        calls:
          - [setTwigEnvironment, [@twig_loader]]
    loop_finder:
        class: %cms.node_loop_finder.class%
    loop_loader:
        class: %cms.node_loop_loader.class%
        arguments: [@loop_finder]
    param_manager:
        class: %cms.param_manager.class%
    node_loader:
        class: %cms.node_loader.class%
    namespace_helper:
        class:  %cms.namespace_helper.class%
    media_storage_factory:
        class: %aws.s3_storage_factory.class%
        arguments: ["%aws.key.param%", "%aws.secret.param%"]
    media_manager:
        class: %cms.media_manager.class%
        arguments: [@media_storage_factory]
        calls:
          - [setBucket, [shinra_test]]
    slug_helper:
        class: %cms.slug_helper.class%
    theme_template:
        class: %cms.theme_template_helper.class%
    site_manager_unique:
        class: %cms.site_manager_unique.class%
        calls:
          - [setPersister, [@persister]]
    check_route:
        class: %cms.check_route.class%
    access_token:
        class: %cms.api_access_token.class%
    api_node_adopter:
        class: %cms.api_node_adopter.class%