Cms\CoreBundle\Document\Site:
    properties:
        state:
          - NotBlank: { message: 'Please add a state' }
          - Choice:
              choices: [active, deleted]
        name:
          - NotBlank: { message: 'Please add a name' }
          - Length:
              min: 2
              max: 63
        namespace:
          - NotBlank: { message: 'Please add a unique namespace' }
          - Length:
              min: 2
              max: 63
        domains:
          - NotBlank: { message: 'Please add a domain' }
          - Type:
              type: array
              message: The value {{ value }} is not a valid {{ type }}.

Cms\CoreBundle\Document\ContentType:
    properties:
        state:
          - NotBlank: { message: 'Please add a state' }
          - Choice:
              choices: [active, deleted, dev]
        name:
          - NotBlank: { message: 'Please add a name' }
          - Length:
              min: 3
              max: 127
        formats:
          - NotBlank: { message: 'Please add at least one format' }
          - Type:
              type: array
              message: The value {{ value }} is not a valid {{ type }}.
        slugPrefix:
          - Length:
              max: 127
        categories:
          - Type:
              type: array
              message: The value {{ value }} is not a valid {{ type }}.
        fields:
          - Type:
              type: array
              message: The value {{ value }} is not a valid {{ type }}.

Cms\CoreBundle\Document\Node:
      properties:
          state:
            - NotBlank: { message: 'Please add a state' }
            - Choice:
                choices: [active, deleted]
          siteId:
            - NotBlank: { message: 'Please add a siteId' }
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}.
          host:
            - NotBlank: { message: 'Please add a hostname' }
            - Length:
                min: 5
                max: 127
          contentTypeName:
            - Length:
                min: 4
                max: 127
          format:
            - NotBlank: { message: 'Please add at least one format' }
            - Length:
                min: 4
                max: 63
          locale:
            - Length: 5
          categories:
            - Type:
                type: array
                message: The value {{ value }} is not a valid {{ type }}.
          tags:
            - Type:
                type: array
                message: The value {{ value }} is not a valid {{ type }}.
          defaultLimit:
            - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
          slug:
            - NotBlank: { message: 'Please add a slug' }
            - Length:
                min: 4
                max: 511
          title:
            - Length:
                min: 1
                max: 127
          templateName:
            - NotBlank: { message: 'Please add a template name' }
            - Length:
                min: 4
                max: 127
          conversationIds:
            - Type:
                type: array
                message: The value {{ value }} is not a valid {{ type }}.
          fields:
            - Type:
                type: array
                message: The value {{ value }} is not a valid {{ type }}.
          author:
            - Type:
                type: array
                message: The value {{ value }} is not a valid {{ type }}.
          view:
            - Type:
                type: array
                message: The value {{ value }} is not a valid {{ type }}.

Cms\CoreBundle\Document\Asset:
    properties:
        name:
           - NotBlank: { message: 'Please add a name' }
           - Length:
              min: 3
              max: 127
        ext:
           - NotBlank: { message: 'Please add an extention' }
           - Choice: { choices: [css, js], message: 'Only js and css extensions are allowed' }
        url:
           - Url: { message: 'Please add a valid URL' }

Cms\CoreBundle\Document\Template:
    properties:
        name:
           - NotBlank: { message: 'Please add a name to tempalte' }
           - Length:
              min: 3
              max: 127
        parent:
           - Length:
              min: 3
              max: 127
        content:
          - Type:
             type: string
             message: The value {{ value }} is not a valid {{ type }}.

Cms\CoreBundle\Document\Media:
    properties:
        siteId:
          - NotBlank: { message: 'Please associate this media file with a site id' }
          - Type:
              type: string
              message: 'siteId must be a string'
        filename:
          - NotBlank: { message: 'Please add a filename' }
          - Type:
              type: string
              message: 'filename must be a string'
        storage:
          - Choice: { choices: [S3], message: 'Storage option is invalid. Please choose: S3' }
        mime:
           - Choice:
              choices: [text/plain, text/csv, text/vcard, application/msword, application/pdf, application/rss+xml, audio/basic, audio/mpeg, audio/x-wav, video/x-msvideo, video/quicktime, video/mp4, video/mpeg, image/jpeg, image/png, gif, image/x-icon ]
              message: A {{ value }} is not a valid file type. Accepted types include: text, csv, vcard, msword, pdf, rss(xml), mpeg, x-wav, msvideo, quicktime, mp4, mpeg, jpeg, png, gif, and x-icon.
        ext:
           - Choice:
              choices: [txt, csv, vcf, doc, docx, pdf, xml, au, mpeg, wav, avi, mov, mp4, jpeg, jpg, png, gif, ico]
              message: The extension {{ value }} is not a valid extion. Valid extensions include: txt, csv, vcf, doc, docx, pdf, xml, au, mpeg, wav, avi, mov, mp4, jpeg, jpg, png, gif and ico.
        size:
           - Type:
              type: integer
              message: 'Invalid filesize'
           - Max: { limit: 10737418240, message: Filesize cannot be larger than 10 gigs. }

