parameters:
    cms_user.force_login.class: Cms\UserBundle\Services\SymfonyTokenForceLogin

services:
    force_login:
        class: %cms_user.force_login.class%
        arguments: [@security.context, "regular"]
