cms_user:
    resource: "@CmsUserBundle/Resources/config/routing.yml"
    prefix:   /

cms_validator:
    resource: "@CmsValidatorBundle/Resources/config/routing.yml"
    prefix:   /

cms_persister:
    resource: "@CmsPersisterBundle/Resources/config/routing.yml"
    prefix:   /

cms_core:
    resource: "@CmsCoreBundle/Resources/config/routing.yml"
    prefix:   /

