jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Cms\UserBundle\Document\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        my_mongo_provider:
            mongodb: {class: Cms\UserBundle\Document\User, property: email}

    firewalls:
        regular:
            pattern : /
            anonymous: ~
            form_login: ~
            logout: ~
            remember_me:
              key:      J8dTf3u3gvVtXB2zOKDF
              lifetime: 31536000 # 365 days in seconds
              path:     /
              domain:   ~ # Defaults to the current domain from $_SERVER

        admin_area:
            pattern:    ^/admin$
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/admin/update, roles: [ROLE_ADMIN] }
        - { path: ^/admin, roles: [ ROLE_ADMIN ] }
