<?php

namespace Cms\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * assetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class assetRepository extends DocumentRepository {

    public function findAllBySiteId($siteId, array $params = array('offset' => 0, 'limit' => 20))
    {
        return $this->createQueryBuilder()
            ->field('siteId')->equals($siteId)
            ->skip($params['offset'])->limit($params['limit'])->getQuery()->execute();
    }
    
}