<?php

namespace Cms\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * assetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class assetRepository extends DocumentRepository {

    public function findAllBySiteId($siteId, array $params = array('offset' => 0, 'limit' => 20))
    {
        return $this->createQueryBuilder()
            ->field('siteId')->equals($siteId)
            ->skip($params['offset'])->limit($params['limit'])->getQuery()->execute();
    }

    public function findAllBySiteIdAndType($siteId, $type, array $params = array('offset' => 0, 'limit' => 20, 'sort' => array('by' => 'created', 'order' => 'desc')))
    {
        $qb = $this->createQueryBuilder()->field('siteId')->equals($siteId);
        if ( isset($type) )
        {
            $qb->field('ext')->equals($type);
        }
        if ( isset($params['search']) )
        {
            $qb->addOr($qb->expr()->field('name')->equals(new \MongoRegex('/.*'.$params['search'].'.*/i')));
        }
        return $qb->sort($params['sort']['by'], $params['sort']['order'])->skip($params['offset'])->limit($params['limit'])->getQuery()->execute();
    }
    
}