<?php

namespace Cms\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * assetHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class assetHistoryRepository extends DocumentRepository {

    public function findAllByParentId($parentId, array $params = array('offset' => 0, 'limit' => 20))
    {
        return $this->createQueryBuilder()
            ->field('parentId')->equals($parentId)
            ->skip($params['offset'])->limit($params['limit'])->getQuery()->execute();
    }
    
}