<?php

namespace Cms\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends DocumentRepository{

    public function findOneByName($name, array $params = array())
    {
        return $this->createQueryBuilder()
            ->field('name')->equals($name)
            ->getQuery()->getSingleResult();
    }
    
}