<?php

namespace Cms\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends DocumentRepository{

    public function findOneByName($name, array $params = array())
    {
        return $this->createQueryBuilder()
            ->field('name')->equals($name)
            ->getQuery()->getSingleResult();
    }

    public function findAllBySiteNamespace($namespace, array $params = array('offset' => 0, 'limit' => 20, 'sort' => array('by' => 'created', 'order' => 'desc')))
    {
        $qb = $this->createQueryBuilder()
            ->field('name')->equals(new \MongoRegex($namespace.'.*/i'));
        if ( isset($params['search']) )
        {
            $qb->expr()->field('content')->equals(new \MongoRegex('/.*'.$params['search'].'.*/i'));
        }
        return $qb->sort($params['sort']['by'], $params['sort']['order'])->skip($params['offset'])->limit($params['limit'])->getQuery()->execute();
    }
    
}