parameters:
    cms_validator.csrfToken: Cms\ValidatorBundle\Services\CsrfToken
    cms_validator.csrfToken_hashAlgo: 'md5'

services:
    csrfToken:
        class: %cms_validator.csrfToken%
        arguments: [@session,  %cms_validator.csrfToken_hashAlgo%]
