parameters:
#    cms_persister.example.class: Cms\PersisterBundle\Example

services:
#    cms_persister.example:
#        class: %cms_persister.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
