parameters:
    persister.class: Cms\PersisterBundle\Services\Persister

services:
    persister:
        class: %persister.class%
        arguments: [@doctrine.odm.mongodb.document_manager, @validator]
